# Generated by bkn-osdk — do not edit.
"""Knowledge network `ecommerce_ops_bkn_public`, branch `main`.

Regenerate with: bkn-osdk generate ecommerce_ops_bkn_public --out <this directory>
"""

from __future__ import annotations

from typing import Any

from bkn_osdk import ObjectType
from bkn_osdk.meta import validate_package
from bkn_osdk.search import search as _search
from bkn_osdk.search import search_instances as _search_instances

from ._meta import (
    BRANCH,
    FORMAT_VERSION,
    GENERATED_BY,
    KN_ID,
    REQUIRES_RUNTIME,
    SCHEMA_FINGERPRINT,
)
from .object_types import (
    Order,
    OrderLine,
    People,
)
from .relation_types import (
    ORDER_TO_BUYER,
    ORDER_TO_LINE,
    RELATION_TYPES,
)
from .metrics import (
    METRICS,
)

validate_package(
    __name__,
    FORMAT_VERSION,
    REQUIRES_RUNTIME,
    kn_id=KN_ID,
    branch=BRANCH,
    fingerprint=SCHEMA_FINGERPRINT,
)

OBJECT_TYPES: tuple[type[ObjectType], ...] = (Order, OrderLine, People)


def search(query: str, **options: Any) -> Any:
    """Search this knowledge network by natural language.

    Network-level rather than object-type-level, which is why it lives here
    and not on a class. Returns the platform's result unchanged.
    """
    return _search(KN_ID, query, **options)


def search_instances(query: str, **options: Any) -> Any:
    """Recall instances of this network by natural language.

    Answers with rows rather than types, across whichever object types have
    a searchable property. Returns the platform's result unchanged.
    """
    return _search_instances(KN_ID, query, **options)


__all__ = [
    "BRANCH",
    "FORMAT_VERSION",
    "GENERATED_BY",
    "KN_ID",
    "METRICS",
    "OBJECT_TYPES",
    "ORDER_TO_BUYER",
    "ORDER_TO_LINE",
    "RELATION_TYPES",
    "REQUIRES_RUNTIME",
    "SCHEMA_FINGERPRINT",
    "Order",
    "OrderLine",
    "People",
    "search",
    "search_instances",
]
