# Generated by bkn-osdk — do not edit.
"""Provenance: what this package was generated from, and what it needs."""

PACKAGE = "bkn"
KN_ID = "ecommerce_ops_bkn_public"
BRANCH = "main"
SCHEMA_FINGERPRINT = "e906b3c569ce09b949a382f6e5d7987e8b32453a6087227e78983fb543cfab08"
FORMAT_VERSION = 1
REQUIRES_RUNTIME = ">=0.1,<0.2"
GENERATED_BY = "bkn-osdk 0.1.0"
