# Generated by bkn-osdk — do not edit.
"""Provenance: what this package was generated from, and what it needs."""

PACKAGE = "bkn"
KN_ID = "ecommerce_ops_bkn_public"
BRANCH = "main"
SCHEMA_FINGERPRINT = "08c2869c5c72cbe67523249855d8a9dfc90d2427deac99d2fa124d648d85ec77"
FORMAT_VERSION = 1
REQUIRES_RUNTIME = ">=0.1,<0.2"
GENERATED_BY = "bkn-osdk 0.1.0"
