# Generated by bkn-osdk — do not edit.
"""Metrics of knowledge network `ecommerce_ops_bkn_public`."""

from __future__ import annotations

from bkn_osdk import Metric


METRICS: tuple[type[Metric], ...] = ()
