# Generated by bkn-osdk — do not edit.
"""Object types of knowledge network `ecommerce_ops_bkn_public`."""

from __future__ import annotations

from datetime import date, datetime, time
from decimal import Decimal
from typing import Any

from bkn_osdk import ObjectType, Property, Relation


class Order(ObjectType):
    """Object type `order`."""

    __kn_id__ = "ecommerce_ops_bkn_public"
    __bkn_id__ = "order"
    __primary_key__ = ("order_id",)
    __display_key__ = "order_no"

    count_ = Property[int]("count")
    created_at = Property[datetime]("created_at")
    discount_rate = Property[float]("discount_rate")
    embedding = Property[Any]("embedding")
    invoice_pdf = Property[bytes]("invoice_pdf")
    is_paid = Property[bool]("is_paid")
    notes = Property[str]("notes")
    order_id = Property[int]("order_id")
    order_no = Property[str]("order_no")
    paid_on = Property[date]("paid_on")
    payload = Property[Any]("payload")
    settled_at = Property[time]("settled_at")
    total_amount = Property[Decimal]("total_amount")

    order_to_buyer = Relation["People"](
        "order_to_buyer",
        target="people",
        join=(),
    )
    order_to_line = Relation["OrderLine"](
        "order_to_line",
        target="order_line",
        join=(("order_id", "order_id"),),
    )


class OrderLine(ObjectType):
    """Object type `order_line`."""

    __kn_id__ = "ecommerce_ops_bkn_public"
    __bkn_id__ = "order_line"
    __primary_key__ = ("order_id", "line_no")

    line_no = Property[int]("line_no")
    order_id = Property[int]("order_id")
    sku = Property[str]("sku")


class People(ObjectType):
    """Object type `people`."""

    __kn_id__ = "ecommerce_ops_bkn_public"
    __bkn_id__ = "people"
    __primary_key__ = ("person_id",)
    __display_key__ = "name"

    age = Property[int]("age")
    name = Property[str]("name")
    person_id = Property[str]("person_id")
