# Generated by bkn-osdk — do not edit.
"""Relation types of knowledge network `ecommerce_ops_bkn_public`."""

from __future__ import annotations

from bkn_osdk import RelationTypeDef

ORDER_TO_BUYER = RelationTypeDef(
    bkn_id="order_to_buyer",
    source="order",
    target="people",
    mapping_rules=(),
)

ORDER_TO_LINE = RelationTypeDef(
    bkn_id="order_to_line",
    source="order",
    target="order_line",
    mapping_rules=(("order_id", "order_id"),),
)

RELATION_TYPES: tuple[RelationTypeDef, ...] = (ORDER_TO_BUYER, ORDER_TO_LINE)
