# Copyright (c) 2026 OpenBKN. All rights reserved.
# Licensed under the Apache License, Version 2.0. See the LICENSE file in the project root.

"""The generator core: `KnSchema` in, a file tree out.

`generate()` is a **pure function** — no HTTP, no filesystem, no clock. Three
shells drive it: the CLI (fetches and writes), the tests (fixture in, golden
files out), and one day the backend (schema in hand, wheel out). Inlining a
fetch or a write here would force a rewrite when that third shell arrives.

Output is byte-stable: plain string templates, sorted iteration, fixed key
order. That is what makes regenerating an unchanged schema produce an empty
`git diff`, which in turn is what makes the diff of a real regeneration the
changelog of the schema change.
"""

from __future__ import annotations

import keyword
from collections.abc import Iterable
from dataclasses import dataclass, field

from ..errors import InputError
from ..schema import (
    KnSchema,
    MetricDef,
    ObjectTypeDef,
    PropertyDef,
    RelationTypeDef,
    fingerprint,
)

__all__ = ["FORMAT_VERSION", "GenOptions", "NamingError", "generate"]

#: Shape of the emitted code. Bumped whenever this module changes what it
#: writes; the runtime supports the current version and the one before it.
FORMAT_VERSION = 1

BANNER = "# Generated by bkn-osdk — do not edit."

#: The BKN specification's standard types. Anything else passes through as
#: `Any`, exactly as the specification says non-standard types pass through.
TYPE_MAP = {
    "string": "str",
    "text": "str",
    "integer": "int",
    "float": "float",
    # The wire carries a decimal as a JSON string ("14485.37"), so Decimal(str)
    # is exact where float would already have lost the value.
    "decimal": "Decimal",
    "boolean": "bool",
    "date": "date",
    "time": "time",
    "datetime": "datetime",
    "json": "Any",
    "binary": "bytes",
}

_IMPORT_OF = {
    "Decimal": ("decimal", "Decimal"),
    "date": ("datetime", "date"),
    "time": ("datetime", "time"),
    "datetime": ("datetime", "datetime"),
    "Any": ("typing", "Any"),
}

#: Query methods every generated class inherits. A property sharing one of these
#: names would shadow it — `Order.count` would stop being callable — so it is
#: suffixed like a keyword and keeps its real id in the descriptor.
RESERVED_ATTRIBUTES = frozenset(
    {
        "count",
        "get",
        "iterate",
        "objects",
        "order_by",
        "page",
        "raw",
        "select",
        "take",
        "where",
        "with_context",
    }
)


class NamingError(InputError):
    """A schema whose ids cannot be turned into Python names without guessing.

    Raised rather than silently disambiguated: two object types that both want
    the name `AB` (`a_b` and `a__b`) are a modelling mistake in the knowledge
    network, and picking `AB2` for one of them would freeze that arbitrary
    choice into every consumer's code.
    """


@dataclass(frozen=True)
class GenOptions:
    """Everything the emitter needs that does not come from the schema.

    Held explicitly rather than read from the environment, so the same schema
    plus the same options always produce the same bytes.
    """

    package: str
    generated_by: str = "bkn-osdk"
    requires_runtime: str = ">=0.1,<0.2"
    format_version: int = FORMAT_VERSION


@dataclass(frozen=True)
class _Named:
    """One schema entity paired with the Python name it was given."""

    name: str
    definition: ObjectTypeDef
    properties: tuple[tuple[str, PropertyDef], ...] = field(default_factory=tuple)
    #: Relations starting at this object type, as (attribute name, definition).
    relations: tuple[tuple[str, RelationTypeDef], ...] = field(default_factory=tuple)


def generate(schema: KnSchema, options: GenOptions) -> dict[str, str]:
    """Emit the package for one knowledge network, as `relative path -> content`.

    Raises `NamingError` before emitting anything, so a schema that cannot be
    named produces no half-written package.
    """
    relations = tuple(sorted(schema.relation_types, key=lambda r: r.bkn_id))
    object_types = tuple(
        _resolve_names(object_type, relations)
        for object_type in sorted(schema.object_types, key=lambda o: o.bkn_id)
    )
    _reject_class_collisions(object_types)
    relation_names = _relation_constants(relations)
    metrics = _named_metrics(schema)

    return {
        "__init__.py": _emit_init(schema, options, object_types, relation_names, metrics),
        "_meta.py": _emit_meta(schema, options),
        "metrics.py": _emit_metrics(schema, metrics),
        "object_types.py": _emit_object_types(schema, object_types),
        "relation_types.py": _emit_relation_types(schema, relations, relation_names),
        "py.typed": "",
    }


# ---- naming -----------------------------------------------------------------


#: Word separators in an object-type id. A hyphen is one as plainly as an
#: underscore — `crm-management-rules` is three words — and treating it as
#: anything else refuses a network the caller does not own and cannot rename.
#: Splitting on both is the same transformation, not a guess: the collision
#: guard still refuses two ids that would land on one name.
_SEPARATORS = ("_", "-", ".", " ")


def class_name(bkn_id: str) -> str:
    """`monitoring_task` -> `MonitoringTask`, keeping the id itself untouched.

    The id survives as `__bkn_id__` and is what the runtime transmits; nothing
    ever reverses a class name back into an id.
    """
    words = bkn_id
    for separator in _SEPARATORS[1:]:
        words = words.replace(separator, "_")
    name = "".join(part[:1].upper() + part[1:] for part in words.split("_") if part)
    if not name:
        raise NamingError(f"Object type id '{bkn_id}' yields no Python class name.")
    # Capitalising already escapes almost every keyword — `class` becomes the
    # perfectly legal `Class`. Only `none`, `true`, and `false` survive it.
    if keyword.iskeyword(name):
        name = f"{name}_"
    if not name.isidentifier():
        raise NamingError(
            f"Object type id '{bkn_id}' yields '{name}', which is not a Python identifier. "
            "Rename the object type in the knowledge network."
        )
    return name


def property_name(bkn_id: str, owner: str) -> str:
    """The attribute a property is reachable under, suffixed only where it must be.

    A separator that is legal in an id and not in an identifier becomes `_`:
    `unit-price` has to be reachable as something, and `unit_price` is the only
    spelling a reader would guess. The wire keeps the id.
    """
    name = bkn_id
    for separator in _SEPARATORS[1:]:
        name = name.replace(separator, "_")
    if keyword.iskeyword(name) or name in RESERVED_ATTRIBUTES:
        name = f"{name}_"
    if not name.isidentifier() or name.startswith("__"):
        raise NamingError(
            f"Property '{bkn_id}' of object type '{owner}' is not a usable Python attribute name."
        )
    return name


def _resolve_names(object_type: ObjectTypeDef, relations: tuple[RelationTypeDef, ...]) -> _Named:
    properties = tuple(
        (property_name(prop.bkn_id, object_type.bkn_id), prop)
        for prop in sorted(object_type.properties, key=lambda p: p.bkn_id)
    )
    _reject_property_collisions(object_type, properties)

    taken = {name for name, _prop in properties}
    outgoing: list[tuple[str, RelationTypeDef]] = []
    for relation in relations:
        if relation.source != object_type.bkn_id:
            continue
        name = relation_attribute(relation.bkn_id, taken)
        taken.add(name)
        outgoing.append((name, relation))

    return _Named(
        name=class_name(object_type.bkn_id),
        definition=object_type,
        properties=properties,
        relations=tuple(outgoing),
    )


def _reject_class_collisions(object_types: tuple[_Named, ...]) -> None:
    seen: dict[str, str] = {}
    for named in object_types:
        clash = seen.get(named.name)
        if clash is not None:
            raise NamingError(
                f"Object types '{clash}' and '{named.definition.bkn_id}' both map to class "
                f"'{named.name}'. Rename one of them in the knowledge network."
            )
        seen[named.name] = named.definition.bkn_id


def _reject_property_collisions(
    object_type: ObjectTypeDef, properties: tuple[tuple[str, PropertyDef], ...]
) -> None:
    seen: dict[str, str] = {}
    for name, prop in properties:
        clash = seen.get(name)
        if clash is not None:
            raise NamingError(
                f"Properties '{clash}' and '{prop.bkn_id}' of object type "
                f"'{object_type.bkn_id}' both map to attribute '{name}'."
            )
        seen[name] = prop.bkn_id


def _relation_constants(relations: tuple[RelationTypeDef, ...]) -> dict[str, str]:
    names: dict[str, str] = {}
    seen: dict[str, str] = {}
    for relation in relations:
        name = relation.bkn_id.upper()
        if not name.isidentifier():
            raise NamingError(f"Relation type id '{relation.bkn_id}' is not a usable Python name.")
        clash = seen.get(name)
        if clash is not None:
            raise NamingError(
                f"Relation types '{clash}' and '{relation.bkn_id}' both map to '{name}'."
            )
        seen[name] = relation.bkn_id
        names[relation.bkn_id] = name
    return names


# ---- emission ---------------------------------------------------------------


def _emit_meta(schema: KnSchema, options: GenOptions) -> str:
    return _file(
        '"""Provenance: what this package was generated from, and what it needs."""',
        "",
        f'PACKAGE = "{options.package}"',
        f'KN_ID = "{schema.kn_id}"',
        f'BRANCH = "{schema.branch}"',
        f'SCHEMA_FINGERPRINT = "{fingerprint(schema)}"',
        f"FORMAT_VERSION = {options.format_version}",
        f'REQUIRES_RUNTIME = "{options.requires_runtime}"',
        f'GENERATED_BY = "{options.generated_by}"',
    )


def relation_attribute(bkn_id: str, taken: set[str]) -> str:
    """The attribute a relation hangs off.

    Relation ids are conventionally prefixed (`rel_order_user`), and the prefix
    says nothing once the attribute already lives on a class — so it is dropped.
    A clash with a property, a query method, or another relation keeps the full
    id rather than inventing a name.
    """
    # Separators first, so a `rel-` prefix is recognised the same as `rel_`.
    name = bkn_id
    for separator in _SEPARATORS[1:]:
        name = name.replace(separator, "_")
    name = name[4:] if name.startswith("rel_") and len(name) > 4 else name
    if not name.isidentifier() or keyword.iskeyword(name) or name in RESERVED_ATTRIBUTES:
        name = bkn_id.replace("-", "_").replace(".", "_").replace(" ", "_")
    if name in taken or keyword.iskeyword(name) or name in RESERVED_ATTRIBUTES:
        name = f"{name}_"
    if not name.isidentifier() or name in taken:
        raise NamingError(
            f"Relation type '{bkn_id}' cannot be given an attribute name on its source "
            f"object type — '{name}' is taken or unusable."
        )
    return name


def _named_metrics(schema: KnSchema) -> tuple[tuple[str, MetricDef], ...]:
    """One class name per metric, keyed off the metric id rather than the mount.

    The same metric can hang off several object types; it is still one metric, so
    it is emitted once and its class records where it was found.
    """
    seen: dict[str, tuple[str, MetricDef]] = {}
    for metric in sorted(schema.metrics, key=lambda m: (m.bkn_id, m.object_type)):
        if metric.bkn_id in seen:
            continue
        name = metric_class_name(metric.bkn_id)
        clash = next((mid for mid, (n, _) in seen.items() if n == name), None)
        if clash is not None:
            raise NamingError(
                f"Metrics '{clash}' and '{metric.bkn_id}' both map to class '{name}'."
            )
        seen[metric.bkn_id] = (name, metric)
    return tuple(seen.values())


def metric_class_name(bkn_id: str) -> str:
    """`m_gmv` -> `Gmv`. The `m_` prefix is a convention, not part of the name."""
    stripped = bkn_id[2:] if bkn_id.startswith("m_") and len(bkn_id) > 2 else bkn_id
    return class_name(stripped)


def _emit_metrics(schema: KnSchema, metrics: tuple[tuple[str, MetricDef], ...]) -> str:
    lines = [
        f'"""Metrics of knowledge network `{schema.kn_id}`."""',
        "",
        "from __future__ import annotations",
        "",
        # Used by the `METRICS` annotation even where the network declares none,
        # so this is not an unused import in the empty case.
        "from bkn_osdk import Metric",
    ]
    for name, metric in metrics:
        lines += [
            "",
            "",
            f"class {name}(Metric):",
            f'    """Metric `{metric.bkn_id}`, mounted on object type `{metric.object_type}`."""',
            "",
            f'    __kn_id__ = "{schema.kn_id}"',
            f'    __bkn_id__ = "{metric.bkn_id}"',
            f'    __object_type__ = "{metric.object_type}"',
            f"    __dimensions__ = {_tuple_literal(metric.dimensions)}",
        ]
    lines += [
        "",
        "",
        f"METRICS: tuple[type[Metric], ...] = "
        f"{_tuple_literal([name for name, _ in metrics], quote=False)}",
    ]
    return _file(*lines)


def _emit_object_types(schema: KnSchema, object_types: tuple[_Named, ...]) -> str:
    used = {
        TYPE_MAP.get(prop.type, "Any") for named in object_types for _name, prop in named.properties
    }
    has_relations = any(named.relations for named in object_types)
    imported = "ObjectType, Property, Relation" if has_relations else "ObjectType, Property"
    lines = [
        f'"""Object types of knowledge network `{schema.kn_id}`."""',
        "",
        "from __future__ import annotations",
        "",
        *_stdlib_imports(used),
        f"from bkn_osdk import {imported}",
    ]
    for named in object_types:
        lines += ["", "", *_emit_class(schema, named)]
    return _file(*lines)


def _emit_class(schema: KnSchema, named: _Named) -> list[str]:
    definition = named.definition
    lines = [
        f"class {named.name}(ObjectType):",
        f'    """Object type `{definition.bkn_id}`."""',
        "",
        f'    __kn_id__ = "{schema.kn_id}"',
        f'    __bkn_id__ = "{definition.bkn_id}"',
        f"    __primary_key__ = {_tuple_literal(definition.primary_key)}",
    ]
    if definition.display_key:
        lines.append(f'    __display_key__ = "{definition.display_key}"')
    if named.properties:
        lines.append("")
    lines += [
        f'    {name} = Property[{TYPE_MAP.get(prop.type, "Any")}]("{prop.bkn_id}")'
        for name, prop in named.properties
    ]
    if named.relations:
        lines.append("")
        lines += _emit_relations(named)
    return lines


def _emit_relations(named: _Named) -> list[str]:
    """One traversable attribute per relation starting here.

    The join columns travel with the declaration, which is what lets a hop be an
    ordinary filtered query on the target type instead of a second grammar.
    """
    return [
        line
        for name, relation in named.relations
        for line in (
            f'    {name} = Relation["{class_name(relation.target)}"](',
            f'        "{relation.bkn_id}",',
            f'        target="{relation.target}",',
            f"        join={_mapping_literal(relation.mapping_rules)},",
            "    )",
        )
    ]


def _emit_relation_types(
    schema: KnSchema, relations: tuple[RelationTypeDef, ...], names: dict[str, str]
) -> str:
    lines = [
        f'"""Relation types of knowledge network `{schema.kn_id}`."""',
        "",
        "from __future__ import annotations",
        "",
        "from bkn_osdk import RelationTypeDef",
    ]
    for relation in relations:
        lines += [
            "",
            f"{names[relation.bkn_id]} = RelationTypeDef(",
            f'    bkn_id="{relation.bkn_id}",',
            f'    source="{relation.source}",',
            f'    target="{relation.target}",',
            # The join columns: traversal needs them, so they are emitted rather
            # than fetched again at query time.
            f"    mapping_rules={_mapping_literal(relation.mapping_rules)},",
            ")",
        ]
    lines += [
        "",
        "RELATION_TYPES: tuple[RelationTypeDef, ...] = "
        f"{_tuple_literal([names[r.bkn_id] for r in relations], quote=False)}",
    ]
    return _file(*lines)


def _emit_init(
    schema: KnSchema,
    options: GenOptions,
    object_types: tuple[_Named, ...],
    relation_names: dict[str, str],
    metrics: tuple[tuple[str, MetricDef], ...] = (),
) -> str:
    class_names = [named.name for named in object_types]
    metric_names = [name for name, _ in metrics]
    exported = _sorted_all(
        [
            "BRANCH",
            "FORMAT_VERSION",
            "GENERATED_BY",
            "KN_ID",
            "OBJECT_TYPES",
            "search",
            "search_instances",
            "RELATION_TYPES",
            "REQUIRES_RUNTIME",
            "SCHEMA_FINGERPRINT",
            *class_names,
            *relation_names.values(),
            *metric_names,
            "METRICS",
        ]
    )
    lines = [
        f'"""Knowledge network `{schema.kn_id}`, branch `{schema.branch}`.',
        "",
        f"Regenerate with: bkn-osdk generate {schema.kn_id} --out <this directory>",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from bkn_osdk import ObjectType",
        "from bkn_osdk.meta import validate_package",
        "from bkn_osdk.search import search as _search",
        "from bkn_osdk.search import search_instances as _search_instances",
        "",
        "from ._meta import (",
        "    BRANCH,",
        "    FORMAT_VERSION,",
        "    GENERATED_BY,",
        "    KN_ID,",
        "    REQUIRES_RUNTIME,",
        "    SCHEMA_FINGERPRINT,",
        ")",
    ]
    if class_names:
        lines += _from_import(".object_types", class_names)
    lines += _from_import(".relation_types", ["RELATION_TYPES", *relation_names.values()])
    # `METRICS` is exported even when the network declares none, so a caller can
    # write `for metric in bkn.METRICS` without first asking whether it exists.
    lines += _from_import(".metrics", ["METRICS", *metric_names])
    lines += [
        "",
        # The one piece of behaviour in a generated package: refuse a runtime
        # that cannot read it, on the import line rather than at the first query.
        # The fingerprint is only registered here — checking it costs a round
        # trip, and `configure(check_schema=True)` is what opts into that.
        "validate_package(",
        "    __name__,",
        "    FORMAT_VERSION,",
        "    REQUIRES_RUNTIME,",
        "    kn_id=KN_ID,",
        "    branch=BRANCH,",
        "    fingerprint=SCHEMA_FINGERPRINT,",
        ")",
        "",
        f"OBJECT_TYPES: tuple[type[ObjectType], ...] = {_tuple_literal(class_names, quote=False)}",
        "",
        "",
        "def search(query: str, **options: Any) -> Any:",
        '    """Search this knowledge network by natural language.',
        "",
        "    Network-level rather than object-type-level, which is why it lives here",
        "    and not on a class. Returns the platform's result unchanged.",
        '    """',
        "    return _search(KN_ID, query, **options)",
        "",
        "",
        "def search_instances(query: str, **options: Any) -> Any:",
        '    """Recall instances of this network by natural language.',
        "",
        "    Answers with rows rather than types, across whichever object types have",
        "    a searchable property. Returns the platform's result unchanged.",
        '    """',
        "    return _search_instances(KN_ID, query, **options)",
        "",
        "",
        "__all__ = [",
        *[f'    "{name}",' for name in exported],
        "]",
    ]
    return _file(*lines)


# ---- primitives -------------------------------------------------------------


def _stdlib_imports(used: set[str]) -> list[str]:
    """Import only what the emitted code uses, in a fixed order."""
    modules: dict[str, set[str]] = {}
    for name in used:
        target = _IMPORT_OF.get(name)
        if target is not None:
            modules.setdefault(target[0], set()).add(target[1])
    lines = [
        f"from {module} import {', '.join(sorted(names))}"
        for module, names in sorted(modules.items())
    ]
    return [*lines, ""] if lines else []


def _sorted_all(names: list[str]) -> list[str]:
    """Constants first, then classes — the order `ruff`'s RUF022 expects.

    Generated code lands in someone else's repository and gets linted there, so
    it is emitted already conforming rather than as a lint finding they cannot
    fix without editing a file that says "do not edit".
    """
    return sorted(names, key=lambda name: (0 if name.isupper() else 1, name))


def _from_import(module: str, names: list[str]) -> list[str]:
    """One name per line — so adding one object type is a one-line diff."""
    if not names:
        return []
    return [f"from {module} import (", *[f"    {name}," for name in sorted(names)], ")"]


def _mapping_literal(rules: Iterable[tuple[str, str]]) -> str:
    pairs = [f'("{source}", "{target}")' for source, target in rules]
    if not pairs:
        return "()"
    if len(pairs) == 1:
        return f"({pairs[0]},)"
    return f"({', '.join(pairs)})"


def _tuple_literal(values: Iterable[object], quote: bool = True) -> str:
    items = [f'"{value}"' if quote else str(value) for value in values]
    if not items:
        return "()"
    if len(items) == 1:
        return f"({items[0]},)"
    return f"({', '.join(items)})"


def _file(*lines: str) -> str:
    return "\n".join([BANNER, *lines]) + "\n"
