# Copyright (c) 2026 OpenBKN. All rights reserved.
# Licensed under the Apache License, Version 2.0. See the LICENSE file in the project root.

"""Emit named functions for the context-loader capability routes.

A pure function, like the ontology generator: contract in, module source out.
The contract is `contracts/kn-rest.json`, frozen from foundry's OpenAPI by
`scripts/capture_kn_contract.py`, so regenerating is a reviewable diff and the
runtime never parses YAML.

What the generated functions buy over `call_tool(name, dict)`:

* the arguments each route declares, with the required ones positional — a
  missing `toolbox_id` is a type error rather than a round trip;
* the **split between query string and body**, which three of these routes have
  and none of them advertise at the call site;
* `bkn_context`, attached by the runtime, so it never appears in a signature;
* the platform's own Chinese prose as docstrings.
"""

from __future__ import annotations

import json
import unicodedata
from typing import Any

__all__ = ["generate_kn_module"]

HEADER = '''# Generated by bkn-osdk — do not edit.
"""Context-loader capability routes, as named functions.

Generated from `contracts/kn-rest.json`, which is frozen from foundry's own
OpenAPI. Every function here is one REST route under
`/api/agent-retrieval/v1/kn/`; the managed turn is attached by the runtime, so
`bkn_context` is never a parameter.

    from bkn_osdk.kn import list_resources, run_sql

    list_resources(kn_id)
    run_sql(kn_id, "SELECT COUNT(*) AS n FROM {{.d9hff…}}")
"""

from __future__ import annotations

from typing import Any

from .config import Context, resolve_context
from .http import request
from .lifecycle import ensure_interaction

__all__ = [
'''

RUNTIME = '''

def _send(
    path: str,
    kn_id: str,
    query: dict[str, Any],
    body: dict[str, Any],
    context: Context | None,
) -> Any:
    """One capability call, on a turn.

    The whole `/kn/` surface refuses a context-free call — including three routes
    whose published request schema does not mention `bkn_context`, which is why
    this does not consult the spec on the question. `ensure_interaction` joins
    the turn already in scope or opens a short-lived one, so a caller never
    builds a `bkn_context` by hand.
    """
    ctx = context or resolve_context()
    arguments = {name: value for name, value in body.items() if value is not None}
    parameters = {name: value for name, value in query.items() if value is not None}
    with ensure_interaction(ctx, kn_id) as turn:
        return request(
            ctx, path, query=parameters or None, body={**arguments, "bkn_context": turn.bkn_context}
        )
'''

#: JSON Schema's types, as a Python annotation. `any` covers what the spec left
#: open — a passthrough block, or a shape it documents in prose instead.
ANNOTATION = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list[Any]",
    "object": "dict[str, Any]",
    "any": "Any",
}


def function_name(operation: str) -> str:
    """A route id as a Python name: `logic-property-resolver` is a path, not an
    identifier, and the wire keeps its own spelling either way."""
    return operation.replace("-", "_")


def generate_kn_module(contract: dict[str, Any]) -> str:
    """The source of `bkn_osdk/kn.py` for this contract."""
    operations = contract["operations"]
    lines = [HEADER]
    lines += [f'    "{function_name(op["operation"])}",\n' for op in operations]
    lines.append("]\n")
    lines.append(RUNTIME)
    for op in operations:
        lines.append(_function(op))
    # No trailing whitespace anywhere: a docstring line that wraps to nothing
    # leaves one, and `ruff format` would then rewrite the file the emitter just
    # wrote — making "regenerate and diff" report a change that is not one.
    return "\n".join(line.rstrip() for line in "".join(lines).split("\n"))


def _function(op: dict[str, Any]) -> str:
    query, body = op["query"], op["body"]
    fields = query + body
    # `kn_id` is the first argument of every function, even the routes that do
    # not send one: `run_sql` finds its data through the placeholder in the SQL,
    # but the turn it runs on still belongs to a knowledge network.

    required = [f for f in fields if f["required"] and f["name"] != "kn_id"]
    optional = [f for f in fields if not f["required"] and f["name"] != "kn_id"]

    signature = ["kn_id: str"]
    signature += [f"{_safe(f['name'])}: {ANNOTATION[f['type']]}" for f in required]
    if optional:
        signature.append("*")
        signature += [
            f"{_safe(f['name'])}: {ANNOTATION[f['type']]} | None = None" for f in optional
        ]
    trailing = "context: Context | None = None"
    signature.append(trailing if optional else f"*, {trailing}")

    def mapping(fields: list[dict[str, Any]]) -> str:
        if not fields:
            return "{}"
        pairs = "".join(f'            "{f["name"]}": {_safe(f["name"])},\n' for f in fields)
        return "{\n" + pairs + "        }"

    return (
        f"\n\ndef {function_name(op['operation'])}(\n"
        + "".join(f"    {part},\n" for part in signature)
        + ") -> Any:\n"
        + _docstring(op)
        + "    return _send(\n"
        + f'        "{op["path"]}",\n'
        + "        kn_id,\n"
        + f"        {mapping(query)},\n"
        + f"        {mapping(body)},\n"
        + "        context,\n"
        + "    )\n"
    )


def _docstring(op: dict[str, Any]) -> str:
    """Google-style, wrapped to fit — the prose is the platform's, verbatim."""
    lines = [f'    """{op["summary"] or op["operation"]}.', ""]
    if op["description"]:
        lines += [f"    {line}" for line in _wrap(op["description"], 90)] + [""]
    if op.get("note"):
        lines += [f"    {line}" for line in _wrap(op["note"], 90)] + [""]

    documented = [f for f in op["query"] + op["body"] if f["description"]]
    if documented:
        lines.append("    Args:")
        for f in documented:
            name = _safe(f["name"])
            # The label eats into the first line's width, and continuations are
            # indented under it, so each gets its own budget.
            described = f["description"]
            if f.get("item_fields"):
                # What goes *in* the list. Without it the annotation says
                # `list[Any]` and the caller learns the shape from a 400.
                described += " 元素字段: " + ", ".join(f["item_fields"]) + "。"
            wrapped = _wrap(described, 90 - _columns(name) - 2)
            lines.append(f"        {name}: {wrapped[0]}")
            lines += [f"            {line}" for line in wrapped[1:]]
        lines.append("")

    if op["returns"]:
        returned = ", ".join(op["returns"])
        lines += [
            f"    {line}" for line in _wrap(f"Returns the platform's own payload: {returned}.", 90)
        ]
    lines.append('    """')
    return "\n".join(lines) + "\n"


def _wrap(text: str, width: int = 74) -> list[str]:
    """Wrap by display width: the platform's prose is Chinese, and a CJK
    character occupies two columns, so counting characters overruns the line
    limit by roughly half."""
    words, line, out = text.split(), "", []
    for word in words:
        if _columns(line) + _columns(word) + 1 > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out or [""]


def _columns(text: str) -> int:
    return sum(2 if unicodedata.east_asian_width(ch) in "WF" else 1 for ch in text)


#: `id` and friends are legal argument names but shadow builtins; the wire name
#: is what goes out, so only the local name changes.
_RESERVED = {"id", "type", "filter", "format", "input", "object"}


def _safe(name: str) -> str:
    safe = name.lstrip("_") or name
    return f"{safe}_" if safe in _RESERVED else safe


def load_contract(path: Any) -> dict[str, Any]:
    """The frozen contract, read from disk."""
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]
